name: MATLAB Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - name: MEX
        uses: matlab-actions/run-command@v1
        with:
          command: copyfile(fullfile(matlabroot,'extern','examples','mex','explore.c'),'.','f'); mex explore.c
