name: MATLAB Build
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        
      - name: Print mexext
        run: mexext.bat
        shell: bash
        
      - name: Print mexext
        run: mexext
        shell: bash
